travis:
  secure:
    BINSTAR_TOKEN: cgNkR9/QoVLg4n9Lwa4C6uqh+JH2H3uSazkaAP24fkbd2IZE2OgWZw1E621eyCguzasuglatFHkgsVo8irj1lst7esu1GxDRdbLWEJXouNygtzFf8gYbOon0XnkrQ3twksH0GIVAr+xbpBta4Va+W+EARICIm9Ja55bk5wUnQetx43LYytsSkFGFvNJx7af81oKfvUSQ+UKwcXi3hQVwcbesx/SQ57B4BeCpnfTczMGZofgHD722/mLTxF88QdJx6laAornwrBsxziD66oek6ehAWl9EJTYxUqU8OIc8AHq1H9dIoQjnsbL/OMamz2pS91CVUgWORgIwo+mljPxntnzVfJgiUIIBgMqQf2r83afShb2BfbB1W6nAGZM3xRdgaH+dh5J3BPkwfYgofWfRLVtv4FhTf6y44XwLpPW6wWDz1CUVjVC0IXabEk1n0reNNSmYrLYHQsiGeGahefLf42k88C7joRpPG9Kn10cQcMhp7k9cBR+OAMNJ/aMXObhayn0qBy40k37nDBEPXffbM2DDYWdgnDlIrzmcbUJaq+TX3RLBf78xN8JziFds7xQ18OQ8Ykw1fyhzV0x2AS59BS6RaT0PKeBA9Vuk5pKYb+g9KNnjO3xWhrxNKH9YAqzRe3GseMCKeRwRa89JjkWDLcqYCjjA2mQQi0EEQp601js=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
