travis:
  secure:
    BINSTAR_TOKEN: LeJgOkY2R9BXAqvK7vfahEfHEx5whJe28M/+o5deyoOthVTlGxsyqe57IZvQ5b1iHGGyCVWx8ZZadBPAgMo5PNpG/Y0MVopwSqVMXkE2gzvzQ2aPNF2PsZvH/v8fvw/xVxXjc6r+mg+hjqQoNXMQ/sNY9RVCwMrmae+4KDwper1lPv12Fm1GGp7d2h15IsfCoFrp/MTfArhYAWSiC8bxqOHoZ1GMtUOUz8ByfUZjCIHOgUerFoDbqk9lNWt6oZ83ZNcBQ8LFGqWFKpsnsV/NCrTX/WdBqBQ4AOwQ4neJhgLUZOxxh+C1uPBwRJf0YJ5wmhj8XMVa+OFiZrnYOXGbFnAjKYZmefBStJk0Q4W7gaQG90+QVb3Wk5CDWA4NDt/uqVy/Y5QaN6JwWu+7QgUk2WnAfTzIxpmpqwsTYRQqgAf0POckwG1I42YQeoVEtTjfeBMOntpIPjdXMn1ZodoGd7JG/hOGXVtlheDWrX0/9HMZFI8plHmiEOpFSa2uivW8ukI9Q5Oy1FuYq+5d62+m88PTS/KVc1h39B8r49O/sRYbzo54hiFbw4ycAySm8ek5DMaBFReFXNRzSzf456/LhYum865JP3I2G+skqz4BeaPrD9ZjXjC99Gn59Pe7vXA92ipK2Oc3tqjPbeLSbe+K7nFirc8lAR/0qOe9h0SP32M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
